# action.yml
name: 'Hello Action'
description: 'Greet someone and record the time'
inputs:
  greet_person_name:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  param_x:  # id of input
    description: 'Param X'
    required: false
    default: '123'
  param_y:  # id of input
    description: 'Param Y'
    required: false
    default: '324'
outputs:
  time: # id of output
    description: 'The time we greeted you'
  sum:
    description: 'Sum of X && Y'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.greet_person_name }}
    - ${{ inputs.param_x }}
    - ${{ inputs.param_y }}