on: [push]

jobs:
  hello_action_job:
    runs-on: ubuntu-latest
    name: A job to say hello and show sum of x / y
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./
        id: test
        with:
          greet_person_name: 'Test User'
          param_x: 77
          param_y: 23
      - name: Get the output time
        run: echo "The time was ${{ steps.test.outputs.time }}"
      - name: Get the output sum
        run: echo "The sum of was ${{ steps.test.outputs.sum }}"